#!/bin/bash
make
let "count = 0"
let "total = 0"
if [ $# -gt "0" ]; then
  echo -n "$1: "
  java Static < "tests/test$1" > "tests/test$1.out"
  if [ ! -r "tests/test$1.out" ];
  then
    echo "FAILED - no output"
  else
    diff "tests/test$1.ref" "tests/test$1.out" > "tests/test$1.diff"
    if [ -s "tests/test$1.diff" ];
    then
      echo "FAILED"
      cat "tests/test$1.diff"
      echo ""
    else
      echo "PASSED"
    fi
  fi
else
   for i in tests/test???
   do
     echo -n "$i: "
     let "total++"
     java Static < $i > $i.out
     if [ ! -r $i.out ];
     then
       echo "FAILED - no output"
     else
       diff $i.ref $i.out > $i.diff
       if [ -s $i.diff ];
       then
         echo "FAILED"
         cat $i.diff
         echo ""
       else
         echo "PASSED"
         let "count++"
       fi
     fi
   done
   echo "Passed $count/$total tests"
fi
